export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  CART_PRODUCTS: "CART_PRODUCTS",
  EMPTY_CART_PRODUCTS: "EMPTY_CART_PRODUCTS",
  TOGGLE: "TOGGLE",
  // INCREASE_QTY: "INCREASE_QTY",
  // DECREASE_QTY: "DECREASE_QTY",
};
